### ISSUE TITLE
Building requires a google account

### ISSUE THREAD

**Issue by mostynb** [bazelbuild/reclient#1]
(Great to see this opensourced, after using the binaries for a long time- thankyou!)

It seems that a google account is required to build (failed build log attached). I have a google account, so I can build locally, but I'm not sure how to set this up for downstream CI builds. What do you suggest?

[reclient_build_log.txt](https://github.com/bazelbuild/reclient/files/12100469/reclient_build_log.txt)

**Comment by gkousik** [comment]
Thanks for filing the issue! From the logs, it looks like you are trying to build re-client on your CI system, with the "--//:include_scanner=goma" option. If it is acceptable, you can try building with "--//:include_scanner=clangscandeps" and that may side-step this issue.

If you do need to build with the goma include-scanner, we have a dependency on https://chromium.googlesource.com/infra/goma/client, which requires an account to be able to download it for building. We don't have any plans to get rid of this requirement at the moment.

Can you describe your CI setup more so that we can understand what could be causing this? Also, I would suggest running on `gclient config https://chromium.googlesource.com/chromium/tools/depot_tools.git` on your CI machine and working through any authentication errors you see (this command should work on a fresh GCP VM without any prior auth).

**Comment by banikharbanda** [comment]
Closing this since it is inactive. Please feel free to file another issue if/when there's a follow up to this.
