### ISSUE TITLE
Temp directory for remote output cause caching difficulties

### ISSUE THREAD

**Issue by nqcuongit95** [bazelbuild/reclient#22]
Hi guys, do we have an option to specify the **temp directory for remote output**? Currently, I'm trying to use **reclient** with **bazel-buildfarm** and I have faced some caching problem because reclient generate temp directory inside the **working directory** which is uploaded to the **bazel-buildfarm** server. The temp dir for remote output is `.reproxy_tmp/ExecutionID` and the `ExecutionID` is different each time I run a remote build, this causes the working directory which is specific as `inputs` for uploading to the server different each time I run a remote build even though for a same action =>the lead to no cache hit problem. As you can see the input tree for a two build action below, the only difference is the **temp directory for remote output**:

![compare_treelayout](https://github.com/bazelbuild/reclient/assets/22268088/2b2744ca-2a16-4859-934f-a3ec35359e03)

This is my rewrapper config:

![image](https://github.com/bazelbuild/reclient/assets/22268088/3a37ee35-df20-4bd7-bca8-7e44db5b1002)

**Comment by gkousik** [comment]
Hi @nqcuongit95 - I want to restate the issue to see if I understand it correctly - you would like reclient to write remote outputs to a temporary directory instead of the actual location of the output file - is that correct?

I understand why you are getting cache misses, but I am not sure how the `.reproxy_tmp/ExecutionID` directory is getting created.

One other thing I noticed is that `out/Debug` is too broad of an input directory (and I"m guessing you are building some variant of Chrome). I would suggest specifying inputs in a fine-grained way rather than in a coarse-grained manner.

**Comment by nqcuongit95** [comment]
Hi @gkousik,

> I want to restate the issue to see if I understand it correctly - you would like reclient to write remote outputs to a temporary directory instead of the actual location of the output file - is that correct?

I mean I would like to have a way to specify the location for the `.reproxy_tmp`, currently I see it is created in the working directory

> One other thing I noticed is that out/Debug is too broad of an input directory (and I"m guessing you are building some variant of Chrome). I would suggest specifying inputs in a fine-grained way rather than in a coarse-grained manner.

Thank you for pointing this out, I will try to make the inputs more fine-grained
