### ISSUE TITLE
Setting the authentication flags results in unable to authenticate with RBE

### ISSUE THREAD

**Issue by Eleanor1216** [bazelbuild/reclient#28]
I just try to use reclient + buildfram to do a regular cpp hello world build . But if I don't set the Authentication flags, it will report an error and let me set it up. If I set the service_no_auth=true, it will report the following error. 

reproxy_config : 
`service_no_auth=true
service_no_security=true
service=$RE_SERVER_ADDRESS
server_address=127.0.0.1:8990
...`
rewrapper_config:
`server_address=127.0.0.1:8990
labels=type=compile,complier=clang,lang=cpp`

Error:
`F0111 17:12:47.842318  164617 main.go:174] Command failed: rpc error: code = Unauthenticated desc = Unable to authenticate with RBE
retry budget exhausted (6 attempts): context deadline exceeded, authentication type (identity) used="no authentication"`

Please tell me how to set up the configuration file to use reclient with bazel-buildfarm. Thank you very much for helping.

**Comment by Eleanor1216** [comment]
Sorry for the problem with my description format. The following is the config file I actually use.
reproxy_config :
![reproxy_config](https://github.com/bazelbuild/reclient/assets/58464765/142729f2-ddc0-4d00-9f67-8f47995c66d0)
rewrapper_config :
![rewrapper_config](https://github.com/bazelbuild/reclient/assets/58464765/415044ed-3fe0-45a2-8593-7b2a2640d628)
Error :
![Error](https://github.com/bazelbuild/reclient/assets/58464765/b3b8ff12-266d-460f-9a84-8b1d0dea2271)

Please tell me how to set up the config file to use reclient with bazel-buildfarm. Thank you very much for helping.

**Comment by Ruoye-W** [comment]
> Thank you very much for helping.

@Eleanor1216  Please confirm if it is port 8990. By default, it seems that the buildfarm uses port 8980. If the connection fails, it will also throw an error indicating authentication failure.

**Comment by Eleanor1216** [comment]
> > Thank you very much for helping.
> 
> @Eleanor1216 Please confirm if it is port 8990. By default, it seems that the buildfarm uses port 8980. If the connection fails, it will also throw an error indicating authentication failure.

According to the docs, reproxy will use -server_address to accept operations from rewrapper. So I set -server_address to 8990. And -service is set to 8980, which is the default port of buildfarm.

**Comment by ywmei-brt1** [comment]
You might passed a invalid value for `service=$RE_SERVER_ADDRESS`.

If you follow buildfarm's quick start doc, [up to but not including section: container-quick-start](https://bazelbuild.github.io/bazel-buildfarm/docs/quick_start/#container-quick-start) : 

You will end with a server running at `8980`, a worker running at `9091`.

Then the minimum configs you might need for re-client is:

reproxy.cfg

```
service=localhost:8980
service_no_auth=true
service_no_security=true
server_address=localhost:8787
```

rewrapper.cfg

```
server_address=localhost:8787
```

Start reproxy via boostrap, and then run some action via rewrapper:

Note that the rewrapper cmd below will not finish (I guess due to the implementation of buildfarm, you can abort the cmd with ctrl+c ), but at least you can get rid of the rpc error.

```
$ ./bootstrap --cfg=reproxy.cfg --re_proxy=./reproxy  
$ ./rewrapper --cfg=rewrapper.cfg --inputs rewrapper.cfg sha256sum rewrapper.cfg # use ctr+c to abort 
$ ./bootstrap --cfg=reproxy.cfg --shutdown
RBE Stats: down 0 B, up 0 B, 1 remote failures 
```

In reproxy.cfg, changing `service=localhost:8980` to anything else (say, `service=foobar`) will lead to the rpc error as shown in comment#2

**Comment by Eleanor1216** [comment]
I tested it as you said and there is indeed a problem with the `service.` There was a problem with our Linux server and the service was not accessible. After modification, we can connect to the buildfarm server. Thank you very much for helping.
