### ISSUE TITLE
What's the purpose of -platform flag in rewrapper?

### ISSUE THREAD

**Issue by GiantPluto** [bazelbuild/reclient#4]
rewrapper has a commandline flag or the config parameter `platform`. The document says
```
-platform (comma-separated key-value pairs)

A set of key=value comma-separated pairs, used to define the remote platform settings (such as the docker container) used to execute the command.
```

What are these set of key-values?

The documentation points to [lexicon page](https://github.com/bazelbuild/remote-apis/blob/main/build/bazel/remote/execution/v2/platform.md) . But I don't see the key `container-image` used in [chromium  ](https://source.chromium.org/chromium/chromium/src/+/main:buildtools/reclient_cfgs/rewrapper_linux.cfg) anywhere documented in the lexicon page. Where can I find more info on what can be used and why is it required?

**Comment by mrahs** [comment]
The lexicon page [defines the standard key-value pairs](https://github.com/bazelbuild/remote-apis/blob/main/build/bazel/remote/execution/v2/platform.md) for the [platform message](https://github.com/bazelbuild/remote-apis/blob/6c32c3b917cc5d3cfee680c03179d7552832bb3f/build/bazel/remote/execution/v2/remote_execution.proto#L713C19-L713C19).

The `container-image` key is not defined in the protocol as a standard key, but is implemented by RBE, Google's implementation of the protocol, which is what chromium uses.

It doesn't look like it's documented, but I can provide a few details. It specifies that the action should run inside docker using the specified container image. That is usually useful when the container includes common inputs, such as a toolchain, which helps relax the requirements on specifying inputs for actions. Otherwise, every action must include a complete list of all inputs, including toolchains, and all inputs must be laid out under the execution root.

**Comment by raphael10-collab** [comment]
@GiantPluto I'm trying to build **`chromium`** as well with `reclient` and `buildbarn` . But I'm having difficulty in setting `reclient`'s flags right . 
Would you be so kind in having a look at here? https://github.com/bazelbuild/reclient/issues/7
